server:
  port: 8081

spring:
  elasticsearch:
    uris: https://localhost:9200
    username: "elastic"
    password: "${password}"
    ssl:
      enabled: true
      certificate-authorities: classpath:http_ca.crt